import streamlit as st
from api_client import get, post, set_flash, show_flash

st.set_page_config(page_title="Playground", page_icon="💬", layout="wide")
st.title("Playground")
st.caption("Send a prompt to an assistant. Every response is auto-evaluated for relevance, groundedness and hallucination risk.")

show_flash()

if "last_result" not in st.session_state:
    st.session_state.last_result = None
if "feedback_given" not in st.session_state:
    st.session_state.feedback_given = {}  # conversation_id -> rating already sent

assistants = get("/assistants") or []
if not assistants:
    st.warning("No assistants found. Run `python seed_data.py` in the backend folder, or create one below.")

with st.expander("Create a new assistant"):
    with st.form("new_assistant"):
        name = st.text_input("Name")
        persona = st.text_input("Persona / description")
        bias = st.slider("Hallucination bias (simulation only)", 0.0, 1.0, 0.15, 0.05)
        if st.form_submit_button("Create assistant"):
            if name.strip():
                post("/assistants", {"name": name, "persona": persona, "hallucination_bias": bias})
                set_flash(f"Assistant '{name}' created.")
                st.rerun()
            else:
                st.warning("Name is required.")

if assistants:
    assistant_names = {a["name"]: a["id"] for a in assistants}
    selected_name = st.selectbox("Assistant", list(assistant_names.keys()))
    assistant_id = assistant_names[selected_name]

    prompt = st.text_area("Prompt", placeholder="e.g. What is your refund policy?")

    if st.button("Send", type="primary") and prompt:
        with st.spinner("Generating and evaluating response..."):
            result = post("/chat", {"assistant_id": assistant_id, "prompt": prompt})
        if result:
            st.session_state.last_result = result

    # Rendered from session_state so it survives reruns triggered by the
    # feedback buttons below (buttons only return True on the exact run
    # they were clicked - putting this outside that run's control flow
    # would silently drop the click, which was the original bug).
    result = st.session_state.last_result
    if result:
        mode = result.get("generation_mode", "mock")
        if mode == "real":
            st.caption("🟢 Generated by real LLM (Gemini)")
        elif mode == "mock_fallback":
            st.caption(f"🟡 Real LLM call failed, fell back to mock — {result.get('generation_error')}")
        else:
            st.caption("⚪ Generated by mock (no API key configured — see Settings)")

        st.markdown("### Response")
        st.write(result["response"])

        eval_data = result["evaluation"]
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Relevance", eval_data["relevance_score"])
        c2.metric("Groundedness", eval_data["groundedness_score"])
        c3.metric("Hallucination risk", eval_data["hallucination_risk"])
        c4.metric("Overall score", eval_data["overall_score"])

        if eval_data["flagged"]:
            st.error("⚠ This response was flagged for governance review.")
        else:
            st.success("This response passed automated checks.")

        with st.expander("Why this score? (explainability)"):
            st.write(eval_data["explanation"])
            st.markdown("**Sources retrieved:**")
            for s in result["used_sources"]:
                st.write(f"- {s['title']}")
            st.markdown("**Retrieval detail:**")
            st.json(result["retrieval_debug"])

        st.markdown("### Feedback")
        conv_id = result["conversation_id"]
        already_given = st.session_state.feedback_given.get(conv_id)

        if already_given:
            st.info(f"Feedback already submitted for this response: {already_given}")
        else:
            fb1, fb2 = st.columns([1, 4])
            with fb1:
                col_up, col_down = st.columns(2)
                if col_up.button("👍", key=f"up_{conv_id}"):
                    post("/feedback", {"conversation_id": conv_id, "rating": "up"})
                    st.session_state.feedback_given[conv_id] = "up"
                    st.rerun()
                if col_down.button("👎", key=f"down_{conv_id}"):
                    post("/feedback", {"conversation_id": conv_id, "rating": "down"})
                    st.session_state.feedback_given[conv_id] = "down"
                    st.rerun()
            with fb2:
                comment = st.text_input("Optional comment", key=f"fb_comment_{conv_id}")
                if st.button("Submit comment", key=f"submit_comment_{conv_id}") and comment:
                    post("/feedback", {"conversation_id": conv_id, "rating": "comment", "comment": comment})
                    st.session_state.feedback_given[conv_id] = "comment"
                    st.rerun()
